trainer: default

dataset:
  train:
    format: ase_db
    src:
      - /path/to/train/dataset
    a2g_args: { r_energy: True, r_forces: True, r_stress: True}

  val:
    format: ase_db
    src:
      - /path/to/valid/dataset
    a2g_args: { r_energy: True, r_forces: True, r_stress: True}
  test:
    format: ase_db
    src:
      - /path/to/test/dataset
    a2g_args: { r_energy: True, r_forces: True, r_stress: True}
#logger: wandbc

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 1
  
  - forces:
      fn: l2mae
      coefficient: 1

evaluation_metrics:
  metrics:
    energy:
      - mae
      - per_atom_mae
    forces:
      - mae
  primary_metric: forces_mae

#distutils
timeout: 200
